#!/bin/sh

# Hector Llorens hack for executing TreeTagger

scriptPath=$(cd $(dirname $0); pwd -P)

BIN=$scriptPath/bin
CMD=$scriptPath/cmd
LIB=$scriptPath/lib

OPTIONS="-token -lemma -pt-with-lemma -no-unknown"

TOKENIZER=${CMD}/tokenize.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/english-abbreviations
PARFILE=${LIB}/english.par
LEXFILE=${LIB}/english-lexicon.txt

$TOKENIZER -e -a $ABBR_LIST $* |
# remove empty lines
grep -v '^$' |
# external lexicon lookup
perl $CMD/lookup.perl $LEXFILE |
# tagging
$TAGGER $OPTIONS $PARFILE | 
perl -pe 's/\tV[BDHV]/\tVB/;s/IN\/that/\tIN/;'
#TOKENIZER=${CMD}/utf8-tokenize.perl

